### PR TITLE
base64_encode: fix several issues

### PR DESCRIPTION
**Pull request by dhobsd**
base64_encode performs out-of-bounds reads on objects that do not have storage sizes divisible by 3 bytes. This is true both for `is_hex` and standard encodings.

When using an alphabet that does not have padding, the returned value from base64_encode incorrectly includes all padding bytes.

Remove unclear / unhelpful comments. Fix issues that comments indicated needed fixing.

Style in this function was starting to get very inconsistent. This has been cleaned up.

### CODE REVIEW

**Comment by gquintard** [comment]
This PR breaks make check (test_hex.vtc to be specific)

**Comment by dhobsd** [comment]
PTAL. I've fixed the issues with `is_hex` (sorry, I really clearly didn't take the time to understand what that was doing, as simple as it is) and greatly simplified the handling of the code around that. I have also removed extraneous `style(9)` changes for otherwise unmodified functions.

**Comment by Dridi** [comment]
Hi @dhobsd, from your commit message it looks like you could split the PR into 4 commits.

Could you please give it a try?

**Comment by gquintard** [comment]
Committed

**Pull request closed without merging**
